// <auto-generated />
using System;
using Knowball.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Knowball.Migrations
{
    [DbContext(typeof(KnowballContext))]
    [Migration("20251010013524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Knowball.Domain.Arbitragem", b =>
                {
                    b.Property<int>("IdPartida")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdArbitro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdPartida", "IdArbitro");

                    b.ToTable("Arbitragens");
                });

            modelBuilder.Entity("Knowball.Domain.Arbitro", b =>
                {
                    b.Property<int>("IdArbitro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArbitro"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValueSql("'Ativo'");

                    b.HasKey("IdArbitro");

                    b.ToTable("Arbitros");
                });

            modelBuilder.Entity("Knowball.Domain.Campeonato", b =>
                {
                    b.Property<int>("IdCampeonato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCampeonato"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCampeonato");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("Knowball.Domain.Denuncia", b =>
                {
                    b.Property<int>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDenuncia"));

                    b.Property<DateTime>("DataDenuncia")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdArbitro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdPartida")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Relato")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ResultadoAnalise")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValueSql("'Em Análise'");

                    b.HasKey("IdDenuncia");

                    b.HasIndex("Protocolo")
                        .IsUnique();

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("Knowball.Domain.Equipe", b =>
                {
                    b.Property<int>("IdEquipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipe"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEquipe");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Knowball.Domain.Participacao", b =>
                {
                    b.Property<int>("IdPartida")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdPartida", "IdEquipe");

                    b.ToTable("Participacoes");
                });

            modelBuilder.Entity("Knowball.Models.Partida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartida"));

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PlacarMandante")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPartida");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Knowball.Domain.Participacao", b =>
                {
                    b.HasOne("Knowball.Models.Partida", null)
                        .WithMany("Participacoes")
                        .HasForeignKey("IdPartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowball.Models.Partida", b =>
                {
                    b.Navigation("Participacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
